### ISSUE TITLE
!iam lets me set my server nickname to the name I already have if I don't have a nickname on the server

### ISSUE THREAD

**Issue by GrayNine** [AllusiveBox/discordBot#21]
Gray NineToday at 5:44 PM
!iam Gray Nine
Spooky ProgBOTToday at 5:44 PM
@Gray Nine, your username has been updated.

**Comment by AllusiveBox** [comment]
Actually realized there were a number of areas that could be improved with this command, so I took the liberty of updating a number of areas that needed addressing. Thanks for bringing this to my attention.

**Comment by AllusiveBox** [comment]
Issue has been resolved and will be included with the next update.
